[functions.detect-and-set-country]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-config]
verify_jwt = false

[functions.automation-cron]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.usdt-rate]
verify_jwt = false

[functions.usdt-auto-verify]
verify_jwt = false

[functions.platform_settings]
verify_jwt = false

project_id = "lamohcoijkpigygiqyih"
