project_id = "lamohcoijkpigygiqyih"

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-config]
verify_jwt = false

[functions.automation-cron]
verify_jwt = false

[functions.send-push]
verify_jwt = false
