// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function userClient(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in UMOJA member's profile (name, email, country, sparks balance, KYC status).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = userClient(ctx);
    const { data, error } = await supabase.from("members").select("id, full_name, email, country, country_code, currency_code, has_contributed, has_buyers_club_access, buyers_club_tier, buyers_club_status, community_score").eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "No member profile found." }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { member: data }
    };
  }
});

// src/lib/mcp/tools/list_my_spark_purchases.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function userClient2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_spark_purchases_default = defineTool2({
  name: "list_my_spark_purchases",
  title: "List my Spark Trade purchases",
  description: "List the signed-in member's Spark Trade product reservations/purchases with status, units, capital allocated, and payment reference.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25)."),
    status: z.string().optional().describe("Optional reservation_status filter, e.g. 'paid', 'reserved', 'shipped'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = userClient2(ctx);
    let query = supabase.from("spark_trade_inventory_reservations").select("id, opportunity_id, units_reserved, total_capital_allocated, reservation_status, payment_reference, reserved_at, paid_at, shipped_at, received_at").eq("member_id", ctx.getUserId()).order("reserved_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("reservation_status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: rows.length ? JSON.stringify(rows, null, 2) : "No purchases found." }],
      structuredContent: { purchases: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/get_platform_info.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_platform_info_default = defineTool3({
  name: "get_platform_info",
  title: "Get UMOJA platform info",
  description: "Return public UMOJA platform info: current bank details, payment instructions, and active circle payout tiers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("platform_settings").select("bank_name, account_name, account_number, branch_code, payment_instructions, payouts_seed, payouts_growth, payouts_harvest, crypto_enabled").order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { platform: data ?? {} }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lamohcoijkpigygiqyih";
var mcp_default = defineMcp({
  name: "umoja-mcp",
  title: "UMOJA",
  version: "0.1.0",
  instructions: "Tools for UMOJA \u2014 a South African community wealth platform (circles, Spark Trade, sparks). Use whoami to identify the signed-in member, list_my_spark_purchases to see the member's Spark Trade orders, and get_platform_info for public banking/payout info.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_my_spark_purchases_default, get_platform_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
